SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(AMOUNT * PRICE) 'TOTAL_SALES'
FROM FOOD_PRODUCT FP, FOOD_ORDER FO
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
AND LEFT(PRODUCE_DATE,7) = '2022-05'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY SUM(FO.AMOUNT * PRICE)DESC, FP.PRODUCT_ID ASC