SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P
INNER JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE D.MCDP_CD = "CS"
AND LEFT(APNT_YMD,10) = '2022-04-13'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC