# 문제링크 : https://school.programmers.co.kr/learn/courses/30/lessons/144856
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES*B.PRICE) AS TOTAL_SALES
FROM AUTHOR A
INNER JOIN BOOK B ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES C ON C.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y%m') = '202201'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC