# 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT DATE_FORMAT(SALES_DATE,"%Y") YEAR
,CAST (DATE_FORMAT(SALES_DATE,"%m") as unsigned) MONTH
,GENDER
,COUNT(DISTINCT OS.USER_ID) USERS
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
;