SELECT LEFT(SALES_DATE,4) "YEAR"
, CASE WHEN LEFT(SUBSTRING_INDEX(SALES_DATE,'-',-2),2) < 10 
        THEN REPLACE(LEFT(SUBSTRING_INDEX(SALES_DATE,'-',-2),2), "0", '') 
    ELSE LEFT(SUBSTRING_INDEX(SALES_DATE,'-',-2),2) 
    END  "MONTH" 
,GENDER
, COUNT(DISTINCT(OS.USER_ID)) "USERS"
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY LEFT(SALES_DATE,4), LEFT(SUBSTRING_INDEX(SALES_DATE,'-',-2),2), GENDER
ORDER BY LEFT(SALES_DATE,4) ASC , LEFT(SUBSTRING_INDEX(SALES_DATE,'-',-2),2), GENDER
;