SELECT   INS.ANIMAL_ID , INS.ANIMAL_TYPE, INS.NAME
FROM     ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE    OUTS.SEX_UPON_OUTCOME != INS.SEX_UPON_INTAKE
ORDER BY ANIMAL_ID