SELECT LEFT(SALES_DATE,10) 'SALES_DATE', PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE ONS
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE OFS
    ) AS T
WHERE LEFT(SALES_DATE,7) = "2022-03"
ORDER BY SALES_DATE , PRODUCT_ID, USER_ID