# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/157341
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE DATE_FORMAT(START_DATE,"%m") = "10"
AND CAR_TYPE = "세단"
ORDER BY C.CAR_ID DESC