#문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/164671

SELECT CONCAT("/home/grep/src/" ,B.BOARD_ID,"/",FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_FILE F ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD B)
ORDER BY FILE_ID DESC