# 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/144855
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES A
INNER JOIN BOOK B ON B.BOOK_ID = A.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY