# 문제링크 : https://school.programmers.co.kr/learn/courses/30/lessons/144854
SELECT BOOK_ID,AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,"%Y-%m-%d") PUBLISHED_DATE
FROM BOOK B
INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE