# 문제링크 : https://school.programmers.co.kr/learn/courses/30/lessons/164673
SELECT TITLE,B.BOARD_ID,REPLY_ID,R.WRITER_ID,R.CONTENTS, LEFT(R.CREATED_DATE,10) CREATED_DATE
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_REPLY R ON R.BOARD_ID = B.BOARD_ID
WHERE LEFT(B.CREATED_DATE,7) = '2022-10'
ORDER BY R.CREATED_DATE, TITLE
