SELECT RR.REST_ID, REST_NAME,FOOD_TYPE, FAVORITES ,ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS 'SCORE'
FROM REST_INFO RI, REST_REVIEW RR
WHERE RR.REST_ID = RI.REST_ID
AND RI.ADDRESS REGEXP '^서울'
GROUP BY RR.REST_ID
ORDER BY ROUND(AVG(REVIEW_SCORE)) DESC , FAVORITES DESC