# 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131120

SELECT MEMBER_ID,MEMBER_NAME,GENDER, LEFT(DATE_OF_BIRTH, 10)
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
AND SUBSTRING(DATE_OF_BIRTH,7,1) = '3'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC