SELECT LEFT(sales_date,4) "YEAR", CAST(mid(sales_date, 6,2) AS UNSIGNED) "MONTH"
, COUNT(DISTINCT OS.USER_ID) "PUCHASED_USERS"
, ROUND(COUNT(DISTINCT OS.USER_ID) 
        / (SELECT COUNT(USER_ID)
    FROM USER_INFO UI
    WHERE LEFT(JOINED,4) = 2021),1) "PUCHASED_RATIO"
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE LEFT(JOINED,4) = 2021
GROUP BY LEFT(sales_date,4), CAST(mid(sales_date, 6,2) AS UNSIGNED)
ORDER BY LEFT(sales_date,4), mid(sales_date, 6,2)